### ISSUE TITLE
could you add a jar please

### ISSUE THREAD

**Issue by transfluxus** [StudioNAND/tact-processing#1]
somewhere

**Comment by narner** [comment]
I would agree with @transfluxus, a .jar file would be super helpful!

**Comment by comkee** [comment]
Releases are published separately and won't be included in this repository. The latest is linked in [readme.md's](https://github.com/StudioNAND/tact-processing/blob/master/readme.md#installation) section titled **Installation**. I'll continue updating this reference – [click to download](https://s3-eu-west-1.amazonaws.com/tact/processing/releases/tact.zip).
